In [3]:
import numpy as np

### Tip_data assignment

In [4]:
table=np.genfromtxt(r"C:\Users\Ammu\Downloads\tipsf word doc.txt",delimiter=",",skip_header=1)

In [5]:
table

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [6]:
np.shape(table)

(244, 8)

In [33]:
# 1.What is the total bill value

In [214]:
Total=table[:,1]

In [215]:
Total_bill_value=np.sum(Total)
print(f"Total bill value:\n{Total_bill_value}")

Total bill value:
4827.77


In [34]:
# 2.What is the total tip value

In [212]:
Total_tip=table[:,2]

In [213]:
Total_tip_value=np.sum(Total_tip)
print(f"Total tip value:\n{Total_tip_value}")

Total tip value:
731.5799999999999


In [35]:
#3.Count how many sun,sat,thu,fri are there

In [45]:
day= np.array(table[:,5])
day_counts=np.unique(day, return_counts=True)
print(day_counts)
sundays_count = np.sum(day == 0)
saturday_count = np.sum(day == 1)
thursday_count = np.sum(day == 2)
friday_count = np.sum(day == 3)
print(f"Number of Sundays: {sundays_count}")
print(f"Number of Saturdays: {saturday_count}")
print(f"Number of thursdays: {thursday_count}")
print(f"Number of fridays: {friday_count}")

(array([0., 1., 2., 3.]), array([87, 76, 62, 19], dtype=int64))
Number of Sundays: 87
Number of Saturdays: 76
Number of thursdays: 62
Number of fridays: 19


In [36]:
#4.How many smokers are there

In [216]:
smoker=table[: ,4]

In [217]:
count_of_smokers = np.count_nonzero(smoker)

In [218]:
print(f"Number of smokers are:{count_of_smokers}")

Number of smokers are:93


In [37]:
#5. What is the avg tip given by male and female

In [239]:
tip=table[:,2]
genders=table[:,3]

In [228]:
seperate_genders=np.unique(genders)
for i in seperate_gender:
    tipsforgender = tip[genders == i].astype(float)
    average_tip = np.mean(tipsforgender)
    gender ="Female" if i == 1 else "Male"
    print(f"Average tip for {gender}: {average_tip:.2f}") 

Average tip for Male: 2.83
Average tip for Female: 3.09


### OR

In [247]:
male=np.where(table[:,3]==0)
a=np.mean(tip[male])
print(f"Average tip for male is:{a}")

Average tip for male is:2.8334482758620685


In [248]:
female=np.where(table[:,3]==1)
b=np.mean(tip[female])
print(f"Average tip for female is:{b}")

Average tip for female is:3.0896178343949043


In [38]:
#6.How much amount have been spent by female and male

In [250]:
total_bill=table[:,1]

In [251]:
male=np.where(table[:,3]==0)
a=np.sum(total_bill[male])
print(f"The amount have been spent by male is :{a}")

The amount have been spent by male is :1570.9499999999996


In [252]:
male=np.where(table[:,3]==1)
bb=np.sum(total_bill[female])
print(f"The amount have been spent by female is :{bb}")

The amount have been spent by female is :3256.8199999999997


In [39]:
#7.What is the min and max tip given

In [254]:
tip=table[:,2]
maxi=np.max(tip)
print(f"The max tip given:{maxi}")

The max tip given:10.0


In [256]:
mini=np.min(tip)
print(f"The min tip given:{mini}")

The min tip given:1.0


In [40]:
#8.How many males and females are going for dinner and lunch

In [7]:
print("Total no.of females going for lunch are: {}".format(np.sum((table[:,3]==1)&(table[:,6]==0))))
print("Total no.of females going for dinner are: {}".format(np.sum((table[:,3]==1)&(table[:,6]==1))))
print("Total no.of males going for lunch are: {}".format(np.sum((table[:,3]==0)&(table[:,6]==0))))
print("Total no.of males going for dinner are: {}".format(np.sum((table[:,3]==0)&(table[:,6]==1))))

Total no.of females going for lunch are: 124
Total no.of females going for dinner are: 33
Total no.of males going for lunch are: 52
Total no.of males going for dinner are: 35


In [41]:
#9.Find out the average size

In [289]:
size=table[:,7]
avg_size=np.mean(size)
print(f"Average size is:{avg_size}")

Average size is:2.569672131147541


In [42]:
#10.How many female smokers are there and male smokers are there

In [8]:
smoker=table[: ,4]
genders=table[:,3]
femalesmokers=np.sum((genders==1)&(smoker==1))
malesmokers=np.sum((genders==0)&(smoker==1))
print(f"Number of Female smokers: {femalesmokers}")
print(f"Number of Male smokers: {malesmokers}")

Number of Female smokers: 60
Number of Male smokers: 33


### Train_Extended data assignment

In [12]:
table2=np.genfromtxt(r"C:\Users\Ammu\Downloads\train_extended doc.txt",delimiter=",", skip_header=1)
print(table2)

[[ 1.575       1.225       0.375      ...  6.3219385   9.63883
  10.        ]
 [ 1.2375      1.          0.375      ...  3.798833    7.654365
  19.        ]
 [ 1.45        1.1625      0.4125     ...  7.01650125  7.257472
  11.        ]
 ...
 [ 1.125       0.9125      0.2875     ...  1.984465    3.118445
   7.        ]
 [ 1.625       1.275       0.4125     ...  7.86698625 10.489315
  11.        ]
 [ 1.5875      1.25        0.3875     ...  7.38504475  8.788345
  11.        ]]


In [9]:
# 1. What is the maximum and minimum length

In [13]:
x = np.max(table2[:,0])
y = np.min(table2[:,0])
print("The maximum length is: ", x)
print("The minimum length is: ", y)

The maximum length is:  7.58349125
The minimum length is:  0.0


In [14]:
# 2. Find out the difference between maximum and minimum length

In [15]:
print("The difference between maximum and minimum length is: ", x-y)

The difference between maximum and minimum length is:  7.58349125


In [16]:
# 3. Find column wise average

In [18]:
print("Average length is: ", np.average(table2[:,0]))
print("Average diameter is: ", np.average(table2[:,1]))
print("Average height is: ", np.average(table2[:,2]))
print("Average weight is: ", np.average(table2[:,3]))
print("Average shucked weight is: ", np.average(table2[:,4]))
print("Average viscera weight is: ", np.average(table2[:,5]))
print("Average shell weight is: ", np.average(table2[:,6]))
print("Average age is: ", np.average(table2[:,7]))

Average length is:  1.3124480799562501
Average diameter is:  1.020320357165
Average height is:  0.34602787104999994
Average weight is:  23.123436312982403
Average shucked weight is:  9.989370248049001
Average viscera weight is:  4.993180956748749
Average shell weight is:  6.634229147607001
Average age is:  9.950615


In [19]:
# 4. Find out all the ages whose height > 0.4

In [20]:
print("The ages with height > 0.4 are: ", table2[:,7][table2[:,2]>0.4])

The ages with height > 0.4 are:  [11. 14. 13. ... 11. 11. 11.]


In [21]:
# 5. What is the average height and weight of persons whose age is 10

In [22]:
print("The average height is: ",np.average(table2[:,2][table2[:,7]==10]))
print("The average weight is: ",np.average(table2[:,3][table2[:,7]==10]))

The average height is:  0.3833672856539947
The average weight is:  28.243308450511314


In [23]:
# 6. What is the total shell weight

In [24]:
print("Total shell weight is: ", np.sum(table2[:,6]))

Total shell weight is:  1326845.8295214002


In [25]:
# 7. How many persons belong to each and every unique age

In [26]:
np.unique(table2[:,-1],return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

In [27]:
# 8. What is the difference between shucked weight and viscera weight

In [28]:
print("The difference between shucked weight and viscera weight is: ", np.sum(table2[:,4])-np.sum(table2[:,5]))

The difference between shucked weight and viscera weight is:  999237.8582600503


In [29]:
# 9. what is the average height of persons whose age is between 14 and 19

In [30]:
print("The average height of persons whose age is between 14 and 19 is: ", np.average(table2[:,2][(table2[:,-1]>14) & (table2[:,-1]<19)]))

The average height of persons whose age is between 14 and 19 is:  0.4190701892744479


In [31]:
# 10. What is the average weight of shucked weight, viscera weight, shell weight

In [32]:
print("The average of shuckedweight,visceraweight,shellweight is:", np.average(np.sum(table2[:,-2])+np.sum(table2[:,-3])+np.sum(table2[:,-4])))

The average of shuckedweight,visceraweight,shellweight is: 4323356.07048095
